USE [POWER_BI_CONTROL];
GO
-- ============================================================
-- 10_sp_evolucion_remision.sql
-- RO_SP_EVOLUCION_REMISION
-- Área 8: Evolución mensual por Tipo de Remisión (Distribución vs Reposición)
--         y Canales (Locales Propios vs Franquicias), con conteo de puntos de
--         venta (locales/franquicias) y promedio por local para evitar sesgo.
--
-- Parámetros:
--   @FECHA_DESDE DATE
--   @FECHA_HASTA DATE
--   @RUBRO       NVARCHAR(100) = NULL
--
-- Result sets:
--   1. Evolución mensual consolidada (Mes, año, nombre_mes, métricas, locales y promedios)
--   2. Resumen período / último mes cerrado (KPIs)
--   3. Detalle mensual para tabla interactiva (incluyendo cant. locales y prom/local)
-- ============================================================

IF OBJECT_ID('dbo.RO_SP_EVOLUCION_REMISION','P') IS NOT NULL
    DROP PROCEDURE dbo.RO_SP_EVOLUCION_REMISION;
GO

CREATE PROCEDURE dbo.RO_SP_EVOLUCION_REMISION
    @FECHA_DESDE DATE,
    @FECHA_HASTA DATE,
    @RUBRO       NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Agrupación base mensual de BI_EFICIENCIA_LOGISTICA
    -- Filtrando únicamente los canales 'LOCALES PROPIOS' y 'FRANQUICIAS'
    -- y los tipos 'DIST. INICIAL' y 'REPOSICION'
    SELECT
        DATEFROMPARTS(YEAR(e.FECHA_PEDI), MONTH(e.FECHA_PEDI), 1) AS MES_FECHA,
        YEAR(e.FECHA_PEDI) AS ANIO,
        MONTH(e.FECHA_PEDI) AS MES_NUM,
        CASE MONTH(e.FECHA_PEDI)
            WHEN 1 THEN 'Ene' WHEN 2 THEN 'Feb' WHEN 3 THEN 'Mar'
            WHEN 4 THEN 'Abr' WHEN 5 THEN 'May' WHEN 6 THEN 'Jun'
            WHEN 7 THEN 'Jul' WHEN 8 THEN 'Ago' WHEN 9 THEN 'Sep'
            WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dic'
        END AS MES_NOMBRE,
        CASE 
            WHEN UPPER(LTRIM(RTRIM(e.CANAL))) LIKE '%PROPIO%' THEN 'PROPIOS'
            ELSE 'FRANQUICIAS'
        END AS CANAL_AGRUP,
        CASE 
            WHEN UPPER(LTRIM(RTRIM(e.TIPO_FACTURACION))) LIKE '%DIST%' THEN 'DISTRIBUCION'
            ELSE 'REPOSICION'
        END AS TIPO_AGRUP,
        e.CLIENTE,
        e.NRO_PEDIDO,
        ISNULL(e.CANT_FACTURADA, 0) AS CANT_FACTURADA,
        ISNULL(e.CANT_PEDID, 0) AS CANT_PEDID
    INTO #BaseRaw
    FROM dbo.BI_EFICIENCIA_LOGISTICA e
    WHERE e.FECHA_PEDI BETWEEN @FECHA_DESDE AND @FECHA_HASTA
      AND UPPER(LTRIM(RTRIM(ISNULL(e.CANAL,'')))) IN ('LOCALES PROPIOS', 'FRANQUICIAS')
      AND UPPER(LTRIM(RTRIM(ISNULL(e.TIPO_FACTURACION,'')))) IN ('DIST. INICIAL', 'DISTRIBUCION', 'REPOSICION')
      AND (@RUBRO IS NULL OR e.RUBRO = @RUBRO);

    -- Agrupado mensual por Canal y Tipo (con distinct de CLIENTE y NRO_PEDIDO)
    SELECT
        MES_FECHA,
        ANIO,
        MES_NUM,
        MES_NOMBRE,
        CANAL_AGRUP,
        TIPO_AGRUP,
        COUNT(DISTINCT CLIENTE) AS CANT_LOCALES,
        COUNT(DISTINCT NRO_PEDIDO) AS CANT_PEDIDOS,
        CAST(SUM(CANT_FACTURADA) AS DECIMAL(18,2)) AS UNID_FACTURADAS,
        CAST(SUM(CANT_PEDID) AS DECIMAL(18,2)) AS UNID_PEDIDAS
    INTO #MensualAgrup
    FROM #BaseRaw
    GROUP BY MES_FECHA, ANIO, MES_NUM, MES_NOMBRE, CANAL_AGRUP, TIPO_AGRUP;

    -- ── Result Set 1: Matriz Mensual con los 5 Universos y sus desgloses ──
    SELECT
        m.MES_FECHA,
        m.ANIO,
        m.MES_NUM,
        m.MES_NOMBRE,
        FORMAT(m.MES_FECHA, 'yyyy-MM') AS PERIODO,
        -- Universo 1: Distribuciones (Propios vs Franquicias)
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.UNID_FACTURADAS END), 0) AS DIST_PROPIOS_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.UNID_FACTURADAS END), 0) AS DIST_FRANQ_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_PEDIDOS END), 0) AS DIST_PROPIOS_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_PEDIDOS END), 0) AS DIST_FRANQ_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_LOCALES END), 0) AS DIST_PROPIOS_LOCALES,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_LOCALES END), 0) AS DIST_FRANQ_LOCALES,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' THEN m.UNID_FACTURADAS END), 0) AS DIST_TOTAL_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' THEN m.CANT_PEDIDOS END), 0) AS DIST_TOTAL_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'DISTRIBUCION' THEN m.CANT_LOCALES END), 0) AS DIST_TOTAL_LOCALES,

        -- Universo 2: Reposiciones (Propios vs Franquicias)
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.UNID_FACTURADAS END), 0) AS REPO_PROPIOS_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.UNID_FACTURADAS END), 0) AS REPO_FRANQ_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_PEDIDOS END), 0) AS REPO_PROPIOS_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_PEDIDOS END), 0) AS REPO_FRANQ_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_LOCALES END), 0) AS REPO_PROPIOS_LOCALES,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' AND m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_LOCALES END), 0) AS REPO_FRANQ_LOCALES,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' THEN m.UNID_FACTURADAS END), 0) AS REPO_TOTAL_UNID,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' THEN m.CANT_PEDIDOS END), 0) AS REPO_TOTAL_PED,
        ISNULL(SUM(CASE WHEN m.TIPO_AGRUP = 'REPOSICION' THEN m.CANT_LOCALES END), 0) AS REPO_TOTAL_LOCALES,

        -- Universo 3: Propios (Distribución vs Reposición)
        ISNULL(SUM(CASE WHEN m.CANAL_AGRUP = 'PROPIOS' THEN m.UNID_FACTURADAS END), 0) AS PROPIOS_TOTAL_UNID,
        ISNULL(SUM(CASE WHEN m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_PEDIDOS END), 0) AS PROPIOS_TOTAL_PED,
        ISNULL(MAX(CASE WHEN m.CANAL_AGRUP = 'PROPIOS' THEN m.CANT_LOCALES END), 0) AS PROPIOS_TOTAL_LOCALES,

        -- Universo 4: Franquicias (Distribución vs Reposición)
        ISNULL(SUM(CASE WHEN m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.UNID_FACTURADAS END), 0) AS FRANQ_TOTAL_UNID,
        ISNULL(SUM(CASE WHEN m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_PEDIDOS END), 0) AS FRANQ_TOTAL_PED,
        ISNULL(MAX(CASE WHEN m.CANAL_AGRUP = 'FRANQUICIAS' THEN m.CANT_LOCALES END), 0) AS FRANQ_TOTAL_LOCALES,

        -- Universo 5: Total General (Distribución vs Reposición)
        ISNULL(SUM(m.UNID_FACTURADAS), 0) AS TOTAL_GENERAL_UNID,
        ISNULL(SUM(m.CANT_PEDIDOS), 0) AS TOTAL_GENERAL_PED

    FROM #MensualAgrup m
    GROUP BY m.MES_FECHA, m.ANIO, m.MES_NUM, m.MES_NOMBRE
    ORDER BY m.MES_FECHA ASC;

    -- ── Result Set 2: KPIs Totales del período seleccionado ──
    SELECT
        CAST(ISNULL(SUM(UNID_FACTURADAS), 0) AS DECIMAL(18,2)) AS TOTAL_UNIDADES,
        ISNULL(SUM(CANT_PEDIDOS), 0) AS TOTAL_PEDIDOS,
        CAST(ISNULL(SUM(CASE WHEN TIPO_AGRUP = 'DISTRIBUCION' THEN UNID_FACTURADAS END), 0) AS DECIMAL(18,2)) AS TOTAL_DIST_UNID,
        ISNULL(SUM(CASE WHEN TIPO_AGRUP = 'DISTRIBUCION' THEN CANT_PEDIDOS END), 0) AS TOTAL_DIST_PED,
        CAST(ISNULL(SUM(CASE WHEN TIPO_AGRUP = 'REPOSICION' THEN UNID_FACTURADAS END), 0) AS DECIMAL(18,2)) AS TOTAL_REPO_UNID,
        ISNULL(SUM(CASE WHEN TIPO_AGRUP = 'REPOSICION' THEN CANT_PEDIDOS END), 0) AS TOTAL_REPO_PED,
        CAST(ISNULL(SUM(CASE WHEN CANAL_AGRUP = 'PROPIOS' THEN UNID_FACTURADAS END), 0) AS DECIMAL(18,2)) AS TOTAL_PROPIOS_UNID,
        ISNULL(SUM(CASE WHEN CANAL_AGRUP = 'PROPIOS' THEN CANT_PEDIDOS END), 0) AS TOTAL_PROPIOS_PED,
        CAST(ISNULL(SUM(CASE WHEN CANAL_AGRUP = 'FRANQUICIAS' THEN UNID_FACTURADAS END), 0) AS DECIMAL(18,2)) AS TOTAL_FRANQ_UNID,
        ISNULL(SUM(CASE WHEN CANAL_AGRUP = 'FRANQUICIAS' THEN CANT_PEDIDOS END), 0) AS TOTAL_FRANQ_PED,
        ISNULL((SELECT COUNT(DISTINCT CLIENTE) FROM #BaseRaw WHERE CANAL_AGRUP = 'PROPIOS'), 0) AS TOTAL_PROPIOS_LOCALES,
        ISNULL((SELECT COUNT(DISTINCT CLIENTE) FROM #BaseRaw WHERE CANAL_AGRUP = 'FRANQUICIAS'), 0) AS TOTAL_FRANQ_LOCALES
    FROM #MensualAgrup;

    -- ── Result Set 3: Detalle por Mes / Canal / Tipo para tabla interactiva ──
    SELECT
        FORMAT(MES_FECHA, 'yyyy-MM') AS PERIODO,
        MES_NOMBRE + ' ' + CAST(ANIO AS VARCHAR(4)) AS MES_ANIO,
        CANAL_AGRUP,
        TIPO_AGRUP,
        CANT_LOCALES,
        CANT_PEDIDOS,
        UNID_FACTURADAS,
        UNID_PEDIDAS,
        CAST(CASE WHEN CANT_LOCALES > 0 THEN UNID_FACTURADAS / CANT_LOCALES ELSE 0 END AS DECIMAL(18,1)) AS PROM_UNID_LOCAL,
        CAST(CASE WHEN CANT_LOCALES > 0 THEN CAST(CANT_PEDIDOS AS FLOAT) / CANT_LOCALES ELSE 0 END AS DECIMAL(18,2)) AS PROM_PED_LOCAL
    FROM #MensualAgrup
    ORDER BY MES_FECHA DESC, CANAL_AGRUP, TIPO_AGRUP;

    DROP TABLE #BaseRaw;
    DROP TABLE #MensualAgrup;
END;
GO
