USE [POWER_BI_CONTROL];
GO
-- ============================================================
-- diag_eficiencia_canal.sql  (v5)
-- ============================================================

DECLARE @DESDE DATE = DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);
DECLARE @AYER  DATE = DATEADD(DAY, -1, CAST(GETDATE() AS DATE));

-- ── 1. Desglose por CANAL + ESTADO_TANGO + TIPO_FACTURACION ──────────────────
--    Foco: entender qué tipo tienen los PENDIENTE de MAYORISTAS
SELECT
    CANAL,
    ESTADO_TANGO,
    TIPO_FACTURACION,
    CAST(SUM(ISNULL(CANT_PEDID,0))     AS DECIMAL(18,0)) AS UNID_PEDIDAS,
    CAST(SUM(ISNULL(CANT_FACTURADA,0)) AS DECIMAL(18,0)) AS UNID_FACTURADAS
FROM dbo.BI_EFICIENCIA_LOGISTICA
WHERE FECHA_PEDI BETWEEN @DESDE AND @AYER
  AND CANAL IN ('MAYORISTAS','LOCALES PROPIOS','FRANQUICIAS')
GROUP BY CANAL, ESTADO_TANGO, TIPO_FACTURACION
ORDER BY CANAL, ESTADO_TANGO, UNID_PEDIDAS DESC;
GO

DECLARE @DESDE DATE = DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);
DECLARE @AYER  DATE = DATEADD(DAY, -1, CAST(GETDATE() AS DATE));

-- ── 2. Eficiencia con filtro original (SF + CANCELADO + DIST. INICIAL) ────────
SELECT
    CANAL,
    CAST(SUM(CASE WHEN ESTADO_TANGO NOT IN ('SIN FACTURAR','CANCELADO')
                       AND ISNULL(TIPO_FACTURACION,'') <> 'DIST. INICIAL'
                  THEN ISNULL(CANT_FACTURADA,0) ELSE 0 END) AS DECIMAL(18,2)) AS UNID_FACTURADAS,
    CAST(SUM(CASE WHEN ESTADO_TANGO NOT IN ('SIN FACTURAR','CANCELADO')
                       AND ISNULL(TIPO_FACTURACION,'') <> 'DIST. INICIAL'
                  THEN ISNULL(CANT_PEDID,0) ELSE 0 END) AS DECIMAL(18,2))     AS UNID_PEDIDAS,
    CAST(100.0 *
        SUM(CASE WHEN ESTADO_TANGO NOT IN ('SIN FACTURAR','CANCELADO')
                      AND ISNULL(TIPO_FACTURACION,'') <> 'DIST. INICIAL'
                 THEN ISNULL(CANT_FACTURADA,0) ELSE 0 END)
        / NULLIF(SUM(CASE WHEN ESTADO_TANGO NOT IN ('SIN FACTURAR','CANCELADO')
                               AND ISNULL(TIPO_FACTURACION,'') <> 'DIST. INICIAL'
                          THEN ISNULL(CANT_PEDID,0) ELSE 0 END), 0)
    AS DECIMAL(5,1)) AS EFI_PCT
FROM dbo.BI_EFICIENCIA_LOGISTICA
WHERE FECHA_PEDI BETWEEN @DESDE AND @AYER
  AND CANAL IS NOT NULL AND LTRIM(RTRIM(CANAL)) <> ''
GROUP BY CANAL
ORDER BY CANAL;
GO
